import './globals.css'
import { Inter, Oswald } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const oswald = Oswald({
  variable: '--font-oswald',
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${oswald.variable}`}>{children}</body>
    </html>
  )
}
